# Generated by Django 4.1.5 on 2023-01-10 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Kategori Açıklama')),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Başlık')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='Açıklama')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('video_link', models.CharField(max_length=250, null=True, verbose_name='Youtube Video Adresi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('image', models.ImageField(default='static/upload/default.jpg', upload_to='static/upload/%Y/%m/%portal', verbose_name='Resim(Önerilen:788x443)')),
                ('slug', models.SlugField(editable=False, max_length=200, null=True, unique=True, verbose_name='Seo Adres')),
                ('views', models.IntegerField(default=0, editable=False, verbose_name='Görüntülenme Sayısı')),
                ('types', models.CharField(choices=[('1', 'Görsel Büyük Tasarımı'), ('2', 'Dengeli Tasarımı'), ('3', 'Text Ağırlıklı Tasarımı')], default='3', max_length=2, verbose_name='Tasarım Tipi')),
                ('table_name', models.CharField(default='video', editable=False, max_length=20)),
                ('available', models.BooleanField(default=False, verbose_name='Yayına Al')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.categories', verbose_name='Kategori')),
            ],
            options={
                'verbose_name_plural': 'Videolar',
                'ordering': ['-created_date'],
            },
        ),
    ]
