# Generated by Django 4.1.5 on 2023-01-13 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Başlık')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='Açıklama')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('image', models.ImageField(default='static/upload/default.jpg', upload_to='static/upload/%Y/%m/%portal', verbose_name='Resim(Önerilen:788x443)')),
                ('slug', models.SlugField(editable=False, max_length=200, null=True, unique=True, verbose_name='Seo Adres')),
                ('views', models.IntegerField(default=0, editable=False, verbose_name='Görüntülenme Sayısı')),
                ('available', models.BooleanField(default=False, verbose_name='Yayına Al')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.categories', verbose_name='Kategori')),
                ('last_edit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edit_video', to=settings.AUTH_USER_MODEL, verbose_name='Düzenleyen Editör')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name_plural': 'Makaleler',
                'ordering': ['-created_date'],
            },
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
